name: Prettier Check

# This action works with pull requests
on:
  pull_request:
    branches:
      - main

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v39

      - name: List all changed files
        run: |
          echo "${{ steps.changed-files.outputs.all_changed_files }}"

      - name: Install Development Dependencies
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - run: npm ci

      - name: Run Prettier
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --check ${{ steps.changed-files.outputs.all_changed_files }}
          prettier_version: 2.8.4
          dry: true